#!/usr/bin/env python3
"""Convert a 160x160 RGB image into an ESP LCD wire-order RGB565 header."""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image


def rgb565_wire(red: int, green: int, blue: int) -> int:
    value = ((red & 0xF8) << 8) | ((green & 0xFC) << 3) | (blue >> 3)
    return ((value << 8) & 0xFFFF) | (value >> 8)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--symbol", default="anime_eye_rgb565_wire")
    args = parser.parse_args()

    with Image.open(args.source) as image:
        image = image.convert("RGB")
        if image.size != (160, 160):
            raise SystemExit(f"Expected 160x160 input, got {image.size}")
        values = [rgb565_wire(*pixel) for pixel in image.getdata()]

    lines = [
        "// Generated by tools/png_to_rgb565.py; do not edit manually.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"static const uint16_t {args.symbol}[160 * 160] = {{",
    ]
    for offset in range(0, len(values), 12):
        chunk = ", ".join(f"0x{value:04X}" for value in values[offset : offset + 12])
        lines.append(f"    {chunk},")
    lines.extend(["};", ""])
    args.output.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
